// =========================================================================
// Copyright 2019 EPAM Systems, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// =========================================================================
#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Epam.CryptoStorage.Droid.Tests.Resource", IsApplication=true)]

namespace Epam.CryptoStorage.Droid.Tests
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::Epam.CryptoStorage.Droid.Tests.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::Epam.CryptoStorage.Droid.Tests.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::Epam.CryptoStorage.Droid.Tests.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::Epam.CryptoStorage.Droid.Tests.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::Epam.CryptoStorage.Droid.Tests.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040001
			public const int OptionHostName = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int OptionPort = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int OptionRemoteServer = 2130968576;
			
			// aapt resource value: 0x7f040010
			public const int OptionsButton = 2130968592;
			
			// aapt resource value: 0x7f04000b
			public const int ResultFullName = 2130968587;
			
			// aapt resource value: 0x7f04000d
			public const int ResultMessage = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int ResultResultState = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int ResultRunSingleMethodTest = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public const int ResultStackTrace = 2130968590;
			
			// aapt resource value: 0x7f040006
			public const int ResultsFailed = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int ResultsId = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int ResultsIgnored = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ResultsInconclusive = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int ResultsMessage = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int ResultsPassed = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int ResultsResult = 2130968580;
			
			// aapt resource value: 0x7f04000f
			public const int RunTestsButton = 2130968591;
			
			// aapt resource value: 0x7f040011
			public const int TestSuiteListView = 2130968593;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int options = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int results = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int test_result = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int test_suite = 2130837508;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
